global:
  scrape_interval: 15s

scrape_configs:
    - job_name: 'onos-exporter'
      metrics_path: "/"
      static_configs:
      - targets: ['exporter:9091']

    - job_name: 'haproxy'
      static_configs:
      - targets: ['host.docker.internal:8405']
